### PR TITLE
fix: compile on MacOS (using Make)

### PR DESCRIPTION
**Pull request by william-silversmith**
Hi nurpax,

I recently became interested in using PNG as a chunk compressor for very large images and saw that spng would provide improved decoding performance compared to Pillow. I updated the build process to use make in order to build MacOS reliably and replaced zlib with miniz for build simplicity (I'm not married to that decision though). I also updated libspng to the latest version as there were some performance enhancements noted in the release notes.

I hope this is a useful contribution. If PNG/spng becomes well adopted by my group, I might contribute some encoder logic as well.

Thanks for your consideration, and I'm willing to adjust this PR to your liking.

Will

### CODE REVIEW

**Comment by william-silversmith** [comment]
This should also fix #4

**Comment by william-silversmith** [comment]
Hi Nurpax, just wanted to check in and see if there's some way I can help resolve any questions or concerns you might have about this PR. If you're busy rn, not feeling well, or something else that's okay! I don't want to burden you with work you don't want. Let me know how you'd like to proceed. Thanks for making this fantastic library!

**Comment by pseudo-rnd-thoughts** [comment]
@william-silversmith Thanks for the PR, I have tried to use it on macos but it doesn't work. Your fork doesn't have issues enabled so I am posting the issue here. The heart of the issue appears to be this
```
      error: invalid argument '-std=c++17' not allowed with 'C'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```
I can most the rest of it if that is helpful

**Comment by william-silversmith** [comment]
I ended making a forked version for now that I think has this issue fixed. Give it a look: https://github.com/seung-lab/pyspng-seunglab

**Comment by nurpax** [comment]
Hi @william-silversmith I must've had my notifications turned off for this project on GH, I never saw this PR or the other one!  Very sorry about this.  I now came back to this project as I noticed that pyspng was failing to build on Python 3.10 and was about to fix that.

I'll take your PR into consideration.  I think I'd like to keep zlib as that's what I'm used to and don't know if miniz has the same type of security battle testing that zlib has undergone (maybe it has?).  But I'll read through these changes anyway and adapt.

**Comment by nurpax** [comment]
Thanks @william-silversmith, I realize you may not be interested in this project after such a long silence.. but anyway I released version 0.1.1 that's inspired by your change.  I'll make a separate change that should fix macOS and upgrade libspng. I didn't move the spng directory with in vendor/libspng-0.7.1 but another change was required for the header `#include` bug.

Would be nice if there was a more direct fix for macOS building.

**Comment by william-silversmith** [comment]
Thanks so much for looking into this! This is a great library and I want to thank you for your work. I've been able to solve my own problems with the fork noted above. I won't have time to go back and merge stuff right now, but please feel free to steal liberally from it. I added a bunch of new features including progressive encoding and a CLI.

**Comment by nurpax** [comment]
For anyone who might across this issue: libspng 0.1.2 should fix a bunch of build problems, including macosx.  I switched to a cmake based build that's quite commonly used in pybind11 projects.

**Pull request closed without merging**
